source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
install! 'cocoapods', :disable_input_output_paths => true

target 'LeakEye_Example' do
  pod 'LeakEye', :path => '../'
  pod 'AppSwizzle', :git => 'git@github.com:dsencheng/AppSwizzle.git'
  target 'LeakEye_Tests' do
    inherit! :search_paths

    
  end
end
